apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Burn Workflow Minutes
on:
  push:
    branches:
      - "branch-001"
jobs:
  job01:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "sleeping for 120"
          sleep 120
          echo "done"
  job02:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "sleeping for 120"
          sleep 120
          echo "done"
  job03:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "sleeping for 120"
          sleep 120
          echo "done"
  job04:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "sleeping for 120"
          sleep 120
          echo "done"
  job05:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "sleeping for 120"
          sleep 120
          echo "done"
  
    needs:
      - job01
      - job02
      - job03
      - job04
          
