apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: burn-hack

on:
  push:
    branches:
      - '**'

jobs:
  burn1:
    steps:
      - name: Burn1
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "sleeping for a long time"
          sleep 18000

  burn2:
    steps:
      - name: Burn2
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "sleeping for a long time"
          sleep 18000
